import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// App language (English / Spanish), no codegen. Every user-visible
/// string goes through tr('English text'); the Spanish table below
/// translates it, and anything missing falls back to the English key
/// itself — so untranslated screens render fine, never crash.
/// Persisted in prefs; MaterialApp listens to [LocaleStore].
class LocaleStore extends ChangeNotifier {
  LocaleStore._();
  static final LocaleStore instance = LocaleStore._();

  static const _key = 'app.lang';
  String _lang = 'en';

  String get lang => _lang;
  bool get isSpanish => _lang == 'es';

  Future<void> init() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final v = prefs.getString(_key) ?? 'en';
      if (v == 'es' || v == 'en') _lang = v;
    } catch (_) {}
  }

  Future<void> setLang(String v) async {
    if (v != 'es' && v != 'en') return;
    if (_lang == v) return;
    _lang = v;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_key, v);
    } catch (_) {}
    notifyListeners();
  }
}

/// Translate [en]: Spanish when selected, else the key itself.
String tr(String en) {
  if (!LocaleStore.instance.isSpanish) return en;
  return _es[en] ?? en;
}

const Map<String, String> _es = {
  'Cancel': 'Cancelar',
  'Close': 'Cerrar',
  'Delete': 'Eliminar',
  'Remove': 'Quitar',
  'Rename': 'Renombrar',
  'Retry': 'Reintentar',
  'Create': 'Crear',
  'Keep queue': 'Mantener cola',
  'Add to queue': 'Añadir a la cola',
  'No connection': 'Sin conexión',
  'OK': 'Vale',
  'Test': 'Probar',
  'Save': 'Guardar',
  'Search': 'Buscar',
  'Reset': 'Restablecer',
  'Connect': 'Conectar',
  'Use': 'Usar',
  'Run': 'Ejecutar',
  'Send': 'Enviar',
  'Fetch': 'Buscar',
  'Copy': 'Copiar',
  'Copy all': 'Copiar todo',
  'Back': 'Atrás',
  'Clear': 'Borrar',
  'Clear all': 'Borrar todo',
  'Never': 'Nunca',
  'Ask me': 'Preguntarme',
  'Change': 'Cambiar',
  'Play': 'Reproducir',
  'Fingerprint': 'Identificar',
  'Versions': 'Versiones',
  'Replace': 'Reemplazar',
  'Download ': 'Descargar ',
  'Downloading ': 'Descargando ',
  'Checking ': 'Revisando ',
  'Matched ': 'Coincide ',
  'Removed ': 'Quitada ',
  'Delete ': 'Eliminar ',
  'Remove ': 'Quitar ',
  'Discard ': 'Descartar ',
  'Added ': 'Añadida ',
  'Playing: ': 'Sonando: ',
  'Channel: ': 'Canal: ',
  'Filename may be WRONG — audio is actually ':
      'El nombre puede estar MAL — el audio es en realidad ',
  'Could not play: ': 'No se pudo reproducir: ',
  'Could not play suggestion: ': 'No se pudo reproducir: ',
  'Import failed: ': 'Falló la importación: ',
  'Could not read playlist: ': 'No se pudo leer la lista: ',
  '…and ': '…y ',
  'Sign in to reach your music and private playlists.':
      'Inicia sesión para ver tu música y tus listas privadas.',
  'Create account': 'Crear cuenta',
  'Pick a username and password. Your playlists stay private to you.':
      'Elige un usuario y una contraseña. Tus listas serán solo tuyas.',
  'Username': 'Usuario',
  'Password': 'Contraseña',
  'Repeat password': 'Repite la contraseña',
  'Invite code (ask the owner)': 'Código de invitación (pídelo al dueño)',
  'Sign in': 'Entrar',
  'Already have an account? Sign in': '¿Ya tienes cuenta? Entra',
  'No account yet? Create one': '¿Sin cuenta? Crea una',
  'Enter a username.': 'Escribe un usuario.',
  'Enter your password.': 'Escribe tu contraseña.',
  'Passwords do not match.': 'Las contraseñas no coinciden.',
  'Password too short (min 6).': 'Contraseña muy corta (mín. 6).',
  'That name is taken — pick another username.':
      'Ese nombre está ocupado — elige otro.',
  'Invalid username or password.': 'Usuario o contraseña no válidos.',
  'Could not reach the server.': 'No se pudo contactar el servidor.',
  'Language': 'Idioma',
  'Library': 'Biblioteca',
  'Downloads': 'Descargas',
  'History': 'Historial',
  'Playlists': 'Listas',
  'Settings': 'Ajustes',
  'Listen history': 'Historial',
  'Songs you played, most recent first':
      'Canciones que escuchaste, recientes primero',
  'Nothing played yet.': 'Nada reproducido aún.',
  'My YT Music Library': 'Mi biblioteca de YT Music',
  'Log in, tick playlists, import all': 'Entra, marca listas e importa todo',
  'From Spotify': 'Desde Spotify',
  'From YouTube Music': 'Desde YouTube Music',
  'Paste a playlist link': 'Pega el enlace de la lista',
  'Import from Spotify': 'Importar desde Spotify',
  'Import from YouTube Music': 'Importar desde YouTube Music',
  'Import playlist': 'Importar lista',
  'The playlist must be public.': 'La lista debe ser pública.',
  'The playlist must be public (unlisted works too).':
      'La lista debe ser pública (oculta también vale).',
  'Playlist link': 'Enlace de la lista',
  'Preview': 'Vista previa',
  'Reading playlist…': 'Leyendo la lista…',
  'No tracks found (private playlist?)': 'Sin canciones (¿lista privada?)',
  'NAS playlist name': 'Nombre de la lista en el NAS',
  'Import': 'Importar',
  'Import a playlist': 'Importar una lista',
  'No playlists yet.': 'Aún no hay listas.',
  'Log in with Google': 'Entrar con Google',
  'Log in with your YouTube (Google) account to see ':
      'Entra con tu cuenta de YouTube (Google) para ver ',
  'Or paste a browser login instead': 'O pega un acceso de navegador',
  'Browser login': 'Acceso de navegador',
  'On any browser, open:': 'En cualquier navegador, abre:',
  'and enter the code:': 'e introduce el código:',
  'Copy code and open link': 'Copiar código y abrir enlace',
  'If Google warns the app isn’t verified: tap Advanced → Go to gungan.fm (unsafe). It’s our own server — Google just hasn’t reviewed it.':
      'Si Google avisa que la app no está verificada: toca Avanzado → Ir a gungan.fm (no seguro). Es nuestro propio servidor — Google aún no lo ha revisado.',
  'Log out': 'Cerrar sesión',
  'YouTube account': 'Cuenta de YouTube',
  'Public channel import (no login needed):':
      'Importar canal público (sin entrar):',
  'Fetching track counts — one moment…': 'Contando canciones — un momento…',
  'Reading playlists…': 'Leyendo listas…',
  'Find playlists': 'Buscar listas',
  'Your YouTube Music library shelves are empty — ':
      'Tu biblioteca de YouTube Music está vacía — ',
  'No playlists on that channel.': 'Ese canal no tiene listas.',
  'Phone cannot reach the server right now — check ':
      'El teléfono no llega al servidor — revisa ',
  'REMOVE': 'QUITAR',
  'PLAY NEXT': 'SIGUIENTE',
  'UNDO': 'DESHACER',
  'Add more': 'Añadir más',
  'Direct track link': 'Enlace directo',
  'Direct video link': 'Enlace de vídeo',
  'Instagram': 'Instagram',
  'Story with artwork': 'Historia con portada',
  'Instagram app not installed': 'App de Instagram no instalada',
  'Instagram isn\'t installed — share to YouTube Music or Spotify instead':
      'Instagram no está instalado — comparte a YouTube Music o Spotify',
  'Link copied to clipboard': 'Enlace copiado',
  'from internet': 'de internet',
  'Play next in queue': 'Siguiente en la cola',
  'Check this song': 'Revisar canción',
  'Add to playlist': 'Añadir a la lista',
  'Lyrics': 'Letra',
  'Run self-test': 'Ejecutar autotest',
  'Recent searches': 'Búsquedas recientes',
  'No matches. Try another spelling.': 'Sin resultados. Prueba otra ortografía.',
  'Starting stream…': 'Iniciando reproducción…',
  'Add to another playlist': 'Añadir a otra lista',
  'Check song': 'Revisar canción',
  'Download to phone': 'Descargar al teléfono',
  'Remove from playlist': 'Quitar de la lista',
  'Delete from every playlist': 'Eliminar de todas las listas',
  'Delete from NAS': 'Eliminar del NAS',
  ' from every playlist?': ' de todas las listas?',
  ' from the NAS?': ' del NAS?',
  'Removed from every playlist': 'Eliminada de todas las listas',
  'Not in any playlist': 'No está en ninguna lista',
  'Only the library owner can delete NAS copies.':
      'Solo el dueño puede eliminar copias del NAS.',
  'No NAS copy found': 'Sin copia en el NAS',
  'Deleted from NAS': 'Eliminada del NAS',
  'The file is gone for everyone. This cannot be undone.':
      'El archivo desaparece para todos. No se puede deshacer.',
  'Empty playlist.': 'Lista vacía.',
  'New playlist': 'Nueva lista',
  'Rename playlist': 'Renombrar lista',
  'Delete playlist': 'Eliminar lista',
  'Reorder': 'Reordenar',
  'Reorder playlist?': '¿Reordenar lista?',
  'Move up': 'Subir',
  'Move down': 'Bajar',
  'Shuffle': 'Aleatorio',
  'Change cover': 'Cambiar portada',
  'Remove cover': 'Quitar portada',
  'Pick a photo from your device': 'Elige una foto de tu dispositivo',
  'Choose from gallery': 'Elegir de la galería',
  'Use art from a song in this playlist':
      'Usar arte de una canción de esta lista',
  'Paste an image URL': 'Pega la URL de una imagen',
  'From URL': 'Desde URL',
  'Image URL': 'URL de imagen',
  'Paste link': 'Pega el enlace',
  'Download playlist': 'Descargar lista',
  'No songs match the search.': 'Ninguna canción coincide.',
  'Removes the playlist and its .m3u file. The music ':
      'Elimina la lista y su archivo .m3u. La música ',
  'Remove custom photo': 'Quitar foto personalizada',
  'Match Spotify order': 'Igualar orden de Spotify',
  'Verify against source': 'Verificar con origen',
  'Retry import': 'Reintentar importación',
  'Retry in same playlist': 'Reintentar en la misma lista',
  'Adding to': 'Añadiendo a',
  'missing': 'faltan',
  'Spotify order': 'Orden de Spotify',
  'Reading Spotify order…': 'Leyendo orden de Spotify…',
  'Spotify playlist link': 'Enlace de lista de Spotify',
  'Paste a public Spotify playlist link (first 100 tracks).':
      'Pega un enlace público de Spotify (primeras 100).',
  'Spotify failed': 'Falló Spotify',
  'No other versions found for this track.':
      'No hay otras versiones de esta canción.',
  'Choose a version to retry': 'Elige una versión para reintentar',
  'Studio originals only': 'Solo originales de estudio',
  'You own this on the NAS': 'La tienes en el NAS',
  'Look & feel': 'Apariencia',
  'Arrange buttons': 'Ordenar botones',
  'Appearance': 'Apariencia',
  'Connection': 'Conexión',
  'Account': 'Cuenta',
  'Deep links': 'Enlaces directos',
  'Check songs': 'Revisar canciones',
  'Check lyrics': 'Revisar letras',
  'Diagnostics': 'Diagnóstico',
  'Phone storage': 'Almacenamiento',
  'On the server (NAS)': 'En el servidor (NAS)',
  'On this phone': 'En este teléfono',
  'Songs': 'Canciones',
  'Import music': 'Importar música',
  'Bottom bar': 'Barra inferior',
  'Arrange player buttons': 'Ordenar botones',
  'Server address': 'Dirección del servidor',
  'Private playlists belong to this account':
      'Las listas privadas pertenecen a esta cuenta',
  'Change password': 'Cambiar contraseña',
  'Needs your current password': 'Necesita tu contraseña actual',
  'Open links by default': 'Abrir enlaces por defecto',
  'Make Spotify and YouTube Music links open here instead of ':
      'Abrir enlaces de Spotify y YouTube Music aquí en vez de ',
  'Whole library': 'Toda la biblioteca',
  'One playlist': 'Una lista',
  'One song…': 'Una canción…',
  'Pick a playlist…': 'Elige una lista…',
  'Verify every downloaded track against its studio original — ':
      'Verifica cada canción contra su original de estudio — ',
  'Verify every NAS song has lyrics that actually belong to it — ':
      'Verifica que cada canción tenga su letra — ',
  'Tap to expand / collapse': 'Toca para abrir / cerrar',
  'Developer tools': 'Herramientas de desarrollo',
  'Photo reports, self-test, player/car logs. Off keeps ':
      'Informes de fotos, autotest, registros. Apagado mantiene ',
  'Artist photo report': 'Informe de fotos de artista',
  'Test the Spotify credentials and dump what Spotify / Deezer ':
      'Prueba Spotify y muestra lo que devuelven Spotify / Deezer ',
  'Device self-test': 'Autotest del dispositivo',
  'Run local + server checks for the open bugs: songs cutting ':
      'Ejecuta pruebas locales y del servidor para los fallos: cortes ',
  'Track restart log': 'Registro de reinicios',
  'Record what the player does around a restart, then share ':
      'Graba lo que hace el reproductor al reiniciar y comparte ',
  'Car session log': 'Registro del coche',
  'Record what the app publishes for the car display, then ':
      'Graba lo que publica la app para el coche y luego ',
  'Share diagnostic logs': 'Compartir registros',
  'Send the restart and car logs (plus a copy saved to the ':
      'Envía los registros (más copia guardada en ',
  'Broadcast': 'Difusión',
  'Test Wrapped': 'Probar Wrapped',
  'Fire a test Wrapped notification with sample stats.':
      'Envía un aviso de Wrapped de prueba con datos de ejemplo.',
  'Test Wrapped sent — check notifications.':
      'Wrapped de prueba enviado — revisa las notificaciones.',
  'Send a notification to all devices now.':
      'Envía una notificación a todos los dispositivos.',
  'Broadcast to apps': 'Difundir a las apps',
  'Send update': 'Enviar actualización',
  'Report': 'Informe',
  'Check versions / replace': 'Versiones / reemplazar',
  'Fingerprint this file': 'Identificar este archivo',
  'Clean/explicit versions exist — listen to confirm yours':
      'Existen versiones limpia/explícita — escucha para confirmar',
  'No studio reference — identity unverified, check manually':
      'Sin referencia de estudio — identidad sin verificar, revisa a mano',
  'OK · matches studio': 'OK · coincide con el estudio',
  'This playlist': 'Esta lista',
  'When offline': 'Sin conexión',
  'Any downloads': 'Cualquier descarga',
  'Limit': 'Límite',
  'Nothing downloaded yet.': 'Nada descargado aún.',
  'Delete all downloads?': '¿Borrar todas las descargas?',
  'Replace the NAS copy?': '¿Reemplazar la copia del NAS?',
  'Versions & replace': 'Versiones y reemplazo',
  'Only the library owner can replace NAS copies.':
      'Solo el dueño puede reemplazar copias del NAS.',
  'No playable copy on the NAS yet (still downloading?).':
      'Aún no hay copia en el NAS (¿descargando?).',
  'No playable NAS file for this song.': 'Sin archivo NAS para esta canción.',
  'Play NAS copy': 'Reproducir copia NAS',
  'Share my Wrapped': 'Compartir mi Wrapped',
  'Preview demo': 'Ver demo',
  'My real Wrapped': 'Mi Wrapped real',
  'Keep listening — your Wrapped unlocks at 30 streams ':
      'Sigue escuchando — tu Wrapped se desbloquea con 30 escuchas ',
  'DEMO · EXIT': 'DEMO · SALIR',
  'Runs local + server checks to pin down bugs we can\'t see from ':
      'Ejecuta pruebas para localizar fallos que no vemos desde ',
  'Browse playlists instead…': 'Ver listas…',
  'Tap to test its first song': 'Toca para probar su primera canción',
  'Play test song': 'Probar canción',
  'Stop test song': 'Detener prueba',
  'It cut here (report early stop)': 'Se cortó aquí (informar)',
  'Copy results': 'Copiar resultados',
  'Results copied to clipboard': 'Resultados copiados',
  'Report copied to clipboard.': 'Informe copiado.',
  '…and more below — type in Search to narrow it down.':
      '…y más abajo — escribe en Buscar para filtrar.',
  'more — refine the search above to see them.':
      'más — afina la búsqueda para verlas.',
  'Wrapped copied': 'Wrapped copiado',
  'BEST MATCH': 'MEJOR RESULTADO',
  'No lyrics found.': 'Sin letra.',
  'Auto app-update notices': 'Avisos de actualización',
  ' (verify what it really is)': ' (verifica qué es en realidad)',
  ' of all time': ' de todos los tiempos',
  ' this year': ' este año',
  '(empty — toggle the log on and reproduce first)':
      '(vacío — activa el registro y reproduce primero)',
  '(queued to download)': '(en cola de descarga)',
  '1 song': '1 canción',
  '@handle, channel name, or UC id': '@usuario, canal o ID UC',
  'ALL TIME': 'TODO EL TIEMPO',
  'ARTIST SPRINT': 'SPRINT DE ARTISTAS',
  'Added': 'Añadido',
  'Added to': 'Añadido a',
  'Added to Liked songs': 'Añadido a Me gusta',
  'Albums': 'Álbumes',
  'All': 'Todas',
  'All downloads': 'Todas las descargas',
  'Already in your NAS library': 'Ya está en tu biblioteca NAS',
  'Already on this phone': 'Ya está en este teléfono',
  'Already on your phone': 'Ya está en tu teléfono',
  'Any': 'Cualquiera',
  'App version': 'Versión de la app',
  'Apply': 'Aplicar',
  'Apr': 'Abr',
  'Artist': 'Artista',
  'Artist name': 'Nombre del artista',
  'Artists': 'Artistas',
  'Audio is': 'El audio es',
  'Aug': 'Ago',
  'Auto': 'Auto',
  'BIGGEST DAY': 'MEJOR DÍA',
  'Background': 'Fondo',
  'Background color': 'Color de fondo',
  'Broadcast sent — devices ping within minutes.':
      'Anuncio enviado — los dispositivos avisan en minutos.',
  'Broadcasts cleared': 'Anuncios borrados',
  'Browser login saved': 'Sesión de navegador guardada',
  "Can't play that link": 'No se puede reproducir ese enlace',
  'Channel': 'Canal',
  'Checking': 'Comprobando',
  'Clean/explicit versions exist at this length — listen to confirm yours.':
      'Existen versiones limpia/explícita con esta duración — escucha para confirmar la tuya.',
  'Compact list': 'Lista compacta',
  'Copied': 'Copiado',
  'Copy the results to hand back.': 'Copia los resultados para pasarlos.',
  'Could not check': 'No se pudo comprobar',
  'Could not fetch that image.': 'No se pudo traer esa imagen.',
  'Could not fingerprint': 'No se pudo identificar',
  'Could not load playlist': 'No se pudo cargar la lista',
  'Could not load playlists': 'No se pudieron cargar las listas',
  'Could not load versions': 'No se pudieron cargar las versiones',
  'Could not open the links settings page': 'No se pudo abrir ajustes de enlaces',
  'Could not open the links settings page.':
      'No se pudo abrir ajustes de enlaces.',
  'Could not play': 'No se pudo reproducir',
  'Could not play suggestion': 'No se pudo reproducir la sugerencia',
  'Could not queue (missing file)': 'No se pudo añadir (falta el archivo)',
  'Could not read playlist': 'No se pudo leer la lista',
  'Could not stream': 'No se pudo transmitir',
  'Cover failed': 'Falló la portada',
  'Cover updated': 'Portada actualizada',
  'Covers grid': 'Cuadrícula de portadas',
  'Current': 'Actual',
  'Current password': 'Contraseña actual',
  'Custom': 'Personalizado',
  'Custom color': 'Color personalizado',
  'Custom photo removed.': 'Foto personalizada eliminada.',
  'Dec': 'Dic',
  'Deleted': 'Eliminada',
  'Discard': 'Descartar',
  'Discarded': 'Descartado',
  'Dismiss': 'Descartar',
  'Done': 'Listo',
  'Download again': 'Descargar otra vez',
  'Downloading': 'Descargando',
  'Downloading again': 'Descargando otra vez',
  'Drag buttons to reorder. Hold one, then drop it on a transport slot to move it there.':
      'Arrastra los botones para reordenar. Mantén uno y suéltalo en un hueco para moverlo.',
  'EPs': 'EPs',
  'Error': 'Error',
  'Error copied': 'Error copiado',
  'Every error, per user: login, download, playback, timeout, import. ':
      'Cada error, por usuario: inicio, descarga, reproducción, espera, importación. ',
  'Failed': 'Falló',
  'Feb': 'Feb',
  'Filename may be WRONG — audio is actually':
      'El nombre puede estar MAL — el audio es en realidad',
  'Fingerprint: audio is': 'Huella: el audio es',
  'Fingerprinting': 'Identificando',
  'Full list': 'Lista completa',
  'High confidence': 'Confianza alta',
  'IN MUSIC': 'EN MÚSICA',
  'Identify': 'Identificar',
  'Import failed': 'Falló la importación',
  'Importing': 'Importando',
  'Infinite queue OFF': 'Cola infinita OFF',
  'Infinite queue ON': 'Cola infinita ON',
  'Jan': 'Ene',
  'Jul': 'Jul',
  'Jun': 'Jun',
  'Keep the next 10 ready for offline listening':
      'Ten las próximas 10 listas para escuchar sin conexión',
  'Length': 'Duración',
  'Like': 'Me gusta',
  'Link (optional)': 'Enlace (opcional)',
  'Listen across months': 'Escucha a lo largo de los meses',
  'Loading songs & albums…': 'Cargando canciones y álbumes…',
  'Loading…': 'Cargando…',
  'Logs copied to clipboard.': 'Registros copiados.',
  'Logs shared.': 'Registros compartidos.',
  'Longer than studio': 'Más larga que el estudio',
  'Look-ahead cache': 'Caché anticipada',
  'Looks fine — matches the studio original':
      'Todo bien — coincide con el original de estudio',
  'Low confidence': 'Confianza baja',
  'Lyrics earlier': 'Letra más atrás',
  'Lyrics later': 'Letra más adelante',
  'Lyrics may be for another song. Got':
      'La letra puede ser de otra canción. Dice',
  'Lyrics present': 'Letra presente',
  'Mar': 'Mar',
  'Matched': 'Coincide',
  'Max lines': 'Máx. líneas',
  'May': 'May',
  'Message': 'Mensaje',
  'Minimize player': 'Minimizar reproductor',
  'NAS': 'NAS',
  'New name': 'Nombre nuevo',
  'New password (min 6)': 'Nueva contraseña (mín 6)',
  'New passwords do not match.': 'Las contraseñas no coinciden.',
  'New playlist name…': 'Nombre de la lista…',
  'No artwork found for that song.': 'Sin arte para esa canción.',
  'No artwork found.': 'Sin arte.',
  'No candidates.': 'Sin candidatos.',
  'No cover found.': 'Sin portada.',
  'No errors found.': 'Sin errores.',
  'No errors logged.': 'Sin errores registrados.',
  'No file matched that name on the NAS.':
      'Ningún archivo coincide con ese nombre en el NAS.',
  'No file to download yet': 'Aún no hay archivo para descargar',
  'No lyrics found': 'Sin letra',
  'No lyrics found for this track.': 'Sin letra para esta canción.',
  'No other playlists.': 'No hay otras listas.',
  'No photo chosen.': 'Sin foto elegida.',
  'No playable NAS file for': 'Sin archivo NAS reproducible para',
  'No playable source for this version.':
      'Sin fuente reproducible para esta versión.',
  'No songs found.': 'Sin canciones.',
  'No songs matched — different playlists?':
      'Sin coincidencias — ¿listas distintas?',
  'No studio reference — identity unverified, check manually.':
      'Sin referencia de estudio — identidad sin verificar, revisa a mano.',
  'No tracks.': 'Sin canciones.',
  'None': 'Ninguna',
  'Not on this phone — connect to play':
      'No está en este teléfono — conéctate para reproducir',
  'Nothing found.': 'Nada encontrado.',
  'Nothing on the server yet.': 'Nada en el servidor todavía.',
  'Nov': 'Nov',
  'Oct': 'Oct',
  'Offline — saved lists. Grey songs need connection.':
      'Sin conexión — listas guardadas. Las grises necesitan conexión.',
  'Offline — server unreachable, showing downloads':
      'Sin conexión — servidor inalcanzable, mostrando descargas',
  'On this phone (': 'En este teléfono (',
  'Opening shared song': 'Abriendo canción compartida',
  'Other songs': 'Otras canciones',
  'Password changed.': 'Contraseña cambiada.',
  'Play anything instantly; save what you like.':
      'Reproduce al instante; guarda lo que te guste.',
  'Play failed': 'Falló la reproducción',
  'Play this NAS song': 'Reproducir esta canción NAS',
  'Playback failed': 'Falló la reproducción',
  'Playing': 'Reproduciendo',
  'Playing next': 'Siguiente',
  'Playlist': 'Lista',
  'Playlist restored': 'Lista restaurada',
  'Prefetch on WiFi only': 'Precarga solo con WiFi',
  'Prefetch upcoming songs': 'Precargar próximas canciones',
  'Enable prefetch?': '¿Activar precarga?',
  'This will download the next 10 queued songs over WiFi so they play offline. Each song is ~5 MB (up to ~50 MB total). Cached songs are auto-removed when space runs low.':
      'Esto descargará las próximas 10 canciones en cola por WiFi para que suenen sin conexión. Cada canción ocupa ~5 MB (hasta ~50 MB en total). Las canciones en caché se eliminan automáticamente cuando falta espacio.',
  'Queue': 'Cola',
  'Reachable — Save to switch.': 'Alcanzable — Guarda para cambiar.',
  'Removed': 'Eliminada',
  'Removed from Liked songs': 'Quitado de Me gusta',
  'Rename failed': 'Falló el renombre',
  'Renamed to': 'Renombrado a',
  'Reorder failed': 'Falló el reorden',
  'Reordered': 'Reordenado',
  'Repeat new password': 'Repite la contraseña',
  'Replace failed': 'Falló el reemplazo',
  'Replace the queue with songs from your phone?':
      '¿Reemplazar la cola con canciones de tu teléfono?',
  'Replaced': 'Reemplazado',
  'Replacement done': 'Reemplazo listo',
  'Replacement failed': 'Reemplazo fallido',
  'Replacement finished': 'Reemplazo terminado',
  'Replacing': 'Reemplazando',
  'Replacing… track it at the top of Check songs.':
      'Reemplazando… míralo arriba en Revisar canciones.',
  'Reset offset': 'Restablecer ajuste',
  'Save the ones you like.': 'Guarda las que te gusten.',
  'Save to playlist': 'Guardar en lista',
  'Saved to': 'Guardado en',
  'Saved to phone': 'Guardado en el teléfono',
  'Search -> pick a track -> it downloads here.':
      'Busca -> elige una canción -> se descarga aquí.',
  'Search NAS + online…': 'Buscar NAS + internet…',
  'Search errors…': 'Buscar errores…',
  'Search internet too': 'Buscar en internet también',
  'Search results': 'Resultados',
  'Search results · near matches': 'Resultados · aproximados',
  'Search songs, artists…': 'Busca canciones, artistas…',
  'Search this playlist…': 'Buscar en esta lista…',
  'Search your NAS library and the internet.':
      'Busca en tu biblioteca NAS e internet.',
  'Search, filter, copy.': 'Busca, filtra, copia.',
  'Select to apply': 'Elige para aplicar',
  'Seen': 'Visto',
  'Selected': 'Elegidas',
  'Sep': 'Sep',
  'Server rejected that link': 'El servidor rechazó ese enlace',
  'Settings clean.': 'Ajustes limpios.',
  'Share': 'Compartir',
  'Share lyrics': 'Compartir letra',
  'Share to YouTube Music': 'Compartir a YouTube Music',
  'Sharing failed': 'Falló compartir',
  'Shorter than studio': 'Más corta que el estudio',
  'Shuffle is for playlist playback':
      'Aleatorio es para reproducir listas',
  'Shuffle off': 'Aleatorio off',
  'Shuffle on': 'Aleatorio on',
  'Shuffle playlist': 'Lista aleatoria',
  'Signed in': 'Sesión iniciada',
  'Singles': 'Sencillos',
  'Slow/broken server link — timeout':
      'Enlace lento/roto — tiempo agotado',
  'Song': 'Canción',
  'Song name to check…': 'Canción a revisar…',
  'Song restored': 'Canción restaurada',
  'Spotify': 'Spotify',
  'Spotify or YouTube Music link → downloads every song ':
      'Enlace de Spotify o YouTube Music → descarga cada canción ',
  'Spotify tracks matched on': 'Canciones de Spotify en',
  'Starting login…': 'Iniciando sesión…',
  'Status': 'Estado',
  'Stop': 'Detener',
  'Stream from internet': 'Transmitir de internet',
  'Suggestions': 'Sugerencias',
  'Tap a playlist to use its cover.': 'Toca una lista para usar su portada.',
  'Tap lines to select': 'Toca líneas para elegir',
  'Testing…': 'Probando…',
  'That name is taken — pick another.': 'Ese nombre está usado — elige otro.',
  'The new audio is in place.': 'El nuevo audio ya está.',
  'The old copy was kept.': 'Se mantuvo la copia anterior.',
  'Theme': 'Tema',
  'Tick playlists to import': 'Marca listas para importar',
  'Tip: press enter to refine the search.':
      'Tip: pulsa enter para afinar la búsqueda.',
  'Title': 'Título',
  'Title + message required.': 'Título + mensaje requeridos.',
  'Too long — maybe live / remix / extended':
      'Muy larga — quizá en vivo / remix / extendida',
  'Too short — possibly censored / cut':
      'Muy corta — quizá censurada / cortada',
  'Try again': 'Reintentar',
  'Unreachable — check the address/network.':
      'Inalcanzable — revisa la dirección/red.',
  'Up next': 'Siguiente',
  'Update available': 'Actualización disponible',
  'Update notice sent — devices ping within minutes.':
      'Aviso enviado — los dispositivos avisan en minutos.',
  'Use a YouTube Music / Spotify cover': 'Usar portada de YouTube Music / Spotify',
  'Use a browser login instead': 'Usar sesión de navegador mejor',
  'User errors': 'Errores de usuarios',
  "Won't fit on the card": 'No cabe en la tarjeta',
  'YOUR TOP ARTISTS': 'TUS TOP ARTISTAS',
  'YOUR TOP SONGS': 'TUS TOP CANCIONES',
  'YouTube Music': 'YouTube Music',
  'Your library': 'Tu biblioteca',
  'a playlist': 'una lista',
  'a song': 'una canción',
  'albums': 'álbumes',
  'and moved to your library': 'y movida a tu biblioteca',
  'app documents folder).': 'carpeta de documentos).',
  'artists': 'artistas',
  'by': 'por',
  'checked': 'revisadas',
  'checked so far': 'revisadas hasta ahora',
  'curl command': 'comando curl',
  'days of music': 'días de música',
  'downloaded — save it': 'descargada — guárdala',
  'failed': 'fallidas',
  'files themselves are NOT deleted.': 'los archivos NO se borran.',
  'fine': 'bien',
  'flags censored, cut, live or wrong versions.':
      'marca censuradas, cortadas, en vivo o erróneas.',
  "flags songs with no lyrics or the wrong song's lyrics.":
      'marca canciones sin letra o con letra ajena.',
  'hours of music': 'horas de música',
  'in NAS': 'en NAS',
  'is ready — tap to download.': 'está lista — toca para descargar.',
  'kept at end': 'quedan al final',
  'line above': 'línea de arriba',
  'line below': 'línea de abajo',
  'minute of music': 'minuto de música',
  'minutes of music': 'minutos de música',
  'minute': 'minuto',
  'minutes': 'minutos',
  'need attention': 'necesitan atención',
  'new version': 'nueva versión',
  'of': 'de',
  'playlist': 'lista',
  'playlists — safe to leave the app.': 'listas — puedes salir de la app.',
  'plays': 'reproducciones',
  'replacement versions available.': 'versiones de reemplazo disponibles.',
  'return for an artist, then copy the report to hand back.':
      'devuelve para un artista, y copia el informe.',
  'rows': 'filas',
  'saved to phone': 'guardadas en el teléfono',
  'score': 'puntaje',
  'share the file. Turn on, connect to the car, share.':
      'comparte el archivo. Activa, conecta al auto, comparte.',
  'short, background audio, playlist latency, missing art. ':
      'corto, audio en fondo, latencia de listas, arte faltante. ',
  'skipped': 'omitidas',
  'so far': 'hasta ahora',
  'song': 'canción',
  'songs': 'canciones',
  'songs into': 'canciones en',
  'songs…': 'canciones…',
  'stream from internet': 'transmitir de internet',
  'streams': 'reproducciones',
  'swapped.': 'cambiada.',
  'sync offset': 'ajuste de letra',
  'tap to use its cover': 'toca para usar su portada',
  'the file. Turn on, reproduce the ~15s restart, share.':
      'el archivo. Activa, reproduce el reinicio de ~15s, comparte.',
  'their own apps.': 'sus propias apps.',
  'this playlist': 'esta lista',
  'to': 'a',
  'to the NAS in order.': 'al NAS en orden.',
  'to unlock the sprint': 'para desbloquear el sprint',
  'total': 'total',
  'tracks': 'canciones',
  'tracks unknown': 'canciones desconocidas',
  'unmatched stay at the end.': 'las demás quedan al final.',
  'via': 'vía',
  'whole library': 'toda la biblioteca',
  '— likely censored / cut': '— quizá censurada / cortada',
  '— likely censored / cut.': '— quizá censurada / cortada.',
  '— maybe live / remix / extended': '— quizá en vivo / remix / extendida',
  '— maybe live / remix / extended.': '— quizá en vivo / remix / extendida.',
  '— old copy kept.': '— copia anterior conservada.',
  '(missing ones stream)': '(las faltantes se transmiten)',
  '1 version to replace with': '1 versión para reemplazar',
  'On NAS': 'En NAS',
  'Play all': 'Reproducir todo',
  'acoustic': 'acústica',
  'alternate': 'alternativa',
  'clean/censored': 'limpia/censurada',
  'instrumental': 'instrumental',
  'live': 'en vivo',
  'remix': 'remix',
  'studio': 'estudio',
  'versions to replace with': 'versiones para reemplazar',
  ' — MISMATCH': ' — NO COINCIDE',
  'Checking fingerprint…': 'Comprobando huella…',
  'Fingerprint hears': 'La huella dice',
  'Fingerprint: no match in database.': 'Huella: sin coincidencia.',
  'Loading versions…': 'Cargando versiones…',
  'No connection — tap play to retry.': 'Sin conexión — toca reproducir.',
  'Replace failed.': 'Reemplazo fallido.',
  'Replaced.': 'Reemplazado.',
  'alternative version': 'versión alternativa',
  's': 's',
  'Nothing playable yet.': 'Nada reproducible todavía.',
  'Pick a song to test': 'Elige una canción para probar',
  'Queue is empty — pick a playlist':
      'Cola vacía — elige una lista',
  'No connection and nothing saved yet.':
      'Sin conexión y nada guardado todavía.',
  'Audio service failed': 'Falló el servicio de audio',
  'more': 'más',
};
